package musicrecognition.services.interfaces;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.security.core.userdetails.User;


public interface UserService {
    /**
     * @return <ul>
     *     <li>id generated by database</li>
     *     <li>null if user is empty or one of the not null fields is empty</li>
     * </ul>
     * @throws DuplicateKeyException if entity violates unique constraint
     * */
    Integer insert(musicrecognition.entities.User user) throws DuplicateKeyException;
    
    User getSpringUserByUsername(String username);
    
    musicrecognition.entities.User dtoToEntity(musicrecognition.dto.User userDto);
}
