package musicrecognition.services.interfaces;

import musicrecognition.dto.UserDto;
import musicrecognition.entities.User;
import org.springframework.dao.DuplicateKeyException;

import java.util.List;


public interface UserService {
    /**
     * @return <ul>
     *     <li>id generated by database</li>
     *     <li>null if user is empty or one of the not null fields is empty</li>
     * </ul>
     * @throws DuplicateKeyException if entity violates unique constraint
     * */
    Integer insert(User user) throws DuplicateKeyException;
    
    /**
     * Maps user DTO to entity and calls insert(user).
     * */
    Integer insert(UserDto userDto);
    
    /**
     * Gets all persistent users, password field is omitted.
     *
     * @return list of users or null if there are no users.
     * */
    List<UserDto> getAll();
    
    org.springframework.security.core.userdetails.User getSpringUserByUsername(String username);
}
