package musicrecognition.dao.interfaces;

import musicrecognition.entities.User;
import org.springframework.dao.DuplicateKeyException;


public interface UserDao {
    /**
     * @return id generated by database
     * @throws DuplicateKeyException if entity violates unique constraint
     * */
    Integer insert(User user) throws DuplicateKeyException;
        
    User getByUsername(String username);
    
    boolean checkIfExists(User user);
}
