package musicrecognition.dao.interfaces;

import musicrecognition.entities.User;
import org.springframework.dao.DuplicateKeyException;

import java.util.List;


public interface UserDao {
    /**
     * @return id generated by database
     * @throws DuplicateKeyException if entity violates unique constraint
     * */
    Integer insert(User user) throws DuplicateKeyException;
        
    User getByUsername(String username);
    
    /**
     * Gets all users from the database, password attribute is omitted.
     *
     * @return list of users or null if there are no users.
     * */
    List<User> getAll();
    
    boolean checkIfExists(User user);
}
